# Generated by Django 6.1.1 on 2026-09-23 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=60, verbose_name="nombre")),
                (
                    "name_en",
                    models.CharField(max_length=60, verbose_name="nombre en inglés"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
            ],
            options={
                "verbose_name": "actividad",
                "verbose_name_plural": "actividades",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="meta")),
                (
                    "target_flux",
                    models.PositiveIntegerField(verbose_name="flux objetivo"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["completed_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trove_name",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="nombre en Trove"
                    ),
                ),
                (
                    "main_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bard", "Bard"),
                            ("Boomeranger", "Boomeranger"),
                            ("Candy Barbarian", "Candy Barbarian"),
                            ("Chloromancer", "Chloromancer"),
                            ("Dino Tamer", "Dino Tamer"),
                            ("Dracolyte", "Dracolyte"),
                            ("Fae Trickster", "Fae Trickster"),
                            ("Gunslinger", "Gunslinger"),
                            ("Ice Sage", "Ice Sage"),
                            ("Knight", "Knight"),
                            ("Lunar Lancer", "Lunar Lancer"),
                            ("Neon Ninja", "Neon Ninja"),
                            ("Pirate Captain", "Pirate Captain"),
                            ("Revenant", "Revenant"),
                            ("Shadow Hunter", "Shadow Hunter"),
                            ("Solarion", "Solarion"),
                            ("Tomb Raiser", "Tomb Raiser"),
                            ("Vanguardian", "Vanguardian"),
                        ],
                        max_length=30,
                        verbose_name="clase principal",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trove_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bard", "Bard"),
                            ("Boomeranger", "Boomeranger"),
                            ("Candy Barbarian", "Candy Barbarian"),
                            ("Chloromancer", "Chloromancer"),
                            ("Dino Tamer", "Dino Tamer"),
                            ("Dracolyte", "Dracolyte"),
                            ("Fae Trickster", "Fae Trickster"),
                            ("Gunslinger", "Gunslinger"),
                            ("Ice Sage", "Ice Sage"),
                            ("Knight", "Knight"),
                            ("Lunar Lancer", "Lunar Lancer"),
                            ("Neon Ninja", "Neon Ninja"),
                            ("Pirate Captain", "Pirate Captain"),
                            ("Revenant", "Revenant"),
                            ("Shadow Hunter", "Shadow Hunter"),
                            ("Solarion", "Solarion"),
                            ("Tomb Raiser", "Tomb Raiser"),
                            ("Vanguardian", "Vanguardian"),
                        ],
                        max_length=30,
                        verbose_name="clase",
                    ),
                ),
                (
                    "power_rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Power Rank"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="inicio"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="fin"),
                ),
                (
                    "flux",
                    models.PositiveIntegerField(default=0, verbose_name="flux ganado"),
                ),
                (
                    "cubits",
                    models.PositiveIntegerField(
                        default=0, verbose_name="cubits ganados"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, max_length=1000, verbose_name="notas"),
                ),
                ("is_logged", models.BooleanField(default=False)),
                (
                    "share_with_community",
                    models.BooleanField(
                        default=True,
                        verbose_name="contar en las estadísticas de la comunidad",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="farm.activity",
                        verbose_name="actividad",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("user",),
                        name="one_running_session_per_user",
                    )
                ],
            },
        ),
    ]
