# Generated by Django 6.1.1 on 2026-09-24 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0002_seed_activities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="farmsession",
            name="external_id",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="farmsession",
            name="source",
            field=models.CharField(
                choices=[("web", "Web"), ("mod", "Mod")], default="web", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="api_key_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="farmsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("user", "external_id"),
                name="unique_external_session",
            ),
        ),
    ]
