# Generated by Django 6.1.1 on 2026-09-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0003_mod_api"),
    ]

    operations = [
        migrations.CreateModel(
            name="LootItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=160)),
                ("name", models.CharField(max_length=120, verbose_name="objeto")),
                ("quantity", models.PositiveIntegerField(verbose_name="cantidad")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loot",
                        to="farm.farmsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-quantity", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "key"), name="unique_loot_per_session"
                    )
                ],
            },
        ),
    ]
